var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/blog/lomthong-pattaya-best-price/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1a2xpb4._.js")
R.c("server/chunks/ssr/node_modules_09r9c10._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0f2u_wg.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xfguxi._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/app_layout_07uf2ib.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/[root-of-the-server]__02slxul._.js")
R.c("server/chunks/ssr/_next-internal_server_app_blog_lomthong-pattaya-best-price_page_actions_0nu6h3y.js")
R.m(1542)
module.exports=R.m(1542).exports
