var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/blog/lomthong-process-pattaya/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0l9rthy._.js")
R.c("server/chunks/ssr/node_modules_09r9c10._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0sz8ko8.js")
R.c("server/chunks/ssr/[root-of-the-server]__0xfguxi._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/app_layout_07uf2ib.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/[root-of-the-server]__02slxul._.js")
R.c("server/chunks/ssr/_next-internal_server_app_blog_lomthong-process-pattaya_page_actions_0o2-l6m.js")
R.m(66166)
module.exports=R.m(66166).exports
